receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
        include_metadata: true

processors:
  batch:
    metadata_keys: 
      - x-honeycomb-team
    metadata_cardinality_limit: 30

  transform/pipeline_steps:
    error_mode: ignore
    trace_statements:
      - statements:
          - set(resource.attributes["otel.collector.path"], "${env:COLLECTOR_NAME}") where resource.attributes["otel.collector.path"] == nil
          - set(resource.attributes["otel.collector.path"], Concat([resource.attributes["otel.collector.path"], "${env:COLLECTOR_NAME}"], " -> ")) where resource.attributes["otel.collector.path"] != nil
          - set(resource.attributes["otel.collector.gateway.pod.name"], "${env:COLLECTOR_NAME}")
    log_statements:
      - statements:
          - set(resource.attributes["otel.collector.path"], "${env:COLLECTOR_NAME}") where resource.attributes["otel.collector.path"] == nil
          - set(resource.attributes["otel.collector.path"], Concat([resource.attributes["otel.collector.path"], "${env:COLLECTOR_NAME}"], " -> ")) where resource.attributes["otel.collector.path"] != nil
          - set(resource.attributes["otel.collector.gateway.pod.name"], "${env:COLLECTOR_NAME}")

exporters:
  debug:
    verbosity: detailed
  file:
    path: ./output.json

extensions:
  headers_setter:
    headers:
      - action: upsert
        key: x-honeycomb-team
        from_context: x-honeycomb-team
    
service:
  extensions: 
    - headers_setter
  pipelines:
    traces:
      receivers: [otlp]
      processors: [transform/pipeline_steps, batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [transform/pipeline_steps, batch]
      exporters: [debug]
  telemetry:
    logs:
      level: debug